---
# defaults file for sachet-role

sachet_install_path: /opt

sachet_group: sachet

sachet_user: sachet

sachet_git_url: https://github.com/messagebird/sachet/releases/download/0.2.0/

sachet_version: sachet-0.2.0.linux-amd64

sachet_bin_path: /usr/local/bin/

sachet_path: /etc/sachet

telegram_token: "724679217:aa26V5mK3e2qkGsSlTT-iHreaa5FUyy3Z_0"
