---
- hosts: all
  become: true
  roles:
    - common
    - icon-monitoring-configs
    - { role: "dev-sec.os-hardening", when: (ansible_hardening | default(false)) }
    - { role: "dev-sec.ssh-hardening", when: (ansible_hardening | default(false)) }
    - { role: "cloudalchemy.prometheus", when: (prometheus_enabled | default(true))}
    - { role: "cloudalchemy.grafana",  when: (grafana_enabled | default(true))}
    - { role: "cloudalchemy.alertmanager",  when: (alertmanager_enabled | default(false))}
    - { role: sachet }

#  tasks:
#    - debug:
#        msg: "{{ grafana_dashboards }}"

  vars:

# File: /etc/grafana...
# API:
#
#    grafana_datasources:
#      - name: prometheus
#        type: prometheus
#        access: proxy
#        url: "http://localhost:9090"
#        basicAuth: false

#    grafana_dashboards:
#      - dashboard_id: 111
#        revision_id: 1
#        datasource: prometheus
#      - path: "{{ playbook_dir }}/templates/"

# alertmanager
    alertmanager_config_file: "{{ playbook_dir }}/templates/alertmanager.yml.j2"

# API: /alerts
    alertmanager_receivers:
      - name: 'slack'
        slack_configs:
         - api_url: "https://hooks.slack.com/services/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"
           channel: "#testchannel"
           text: thing
#           text: "Overview: {{ .CommonAnnotations.overview }}"
#           text: "Overview: {{ .CommonAnnotations.description }}"

    alertmanager_route:
      group_by: ['slack']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 30m
      receiver: 'slack'

#      routes:
#        - match:
#            team: devops

    alertmanager_resolve_timeout: 5m
    alertmanager_smtp:
      from: 'prometheus'
      smarthost: 'localhost:25'
#     auth_username: ''
#     auth_password: ''
#     auth_secret: ''
#     auth_identity: ''
#     require_tls: "True"